security:
  # Ideally you would store this externally.
  firebase:
    databaseUrl: https://project-id.firebaseio.com
  jwt:
    url: /auth/
    header: Authorization
    prefix: 'Bearer '
    expiration: 3600
    secret: <my-secret>
  service:
    username: <service-account>
    password: <service-password>
    role: SERVICE
  twilio:
    url: /sms/
    sid: <sid>
    authToken: <auth-token>