apiVersion: apps/v1
kind: Deployment
metadata:
  name: indy-oracle-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indy-oracle
      tier: ui
  template:
    metadata:
      labels:
        app: indy-oracle
        tier: ui
    spec:
      containers:
      - name: indy-oracle-ui
        image: my/repo/indy-oracle-ui:1.0.0
        ports:
        - containerPort: 3000